# Generated by Django 5.1.1 on 2024-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во комментариев'),
        ),
    ]
