# Generated by Django 5.1.1 on 2024-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('image', models.ImageField(default='default.jpg', upload_to='game_images', verbose_name='Изображение игры')),
                ('description', models.TextField(verbose_name='Краткое описание игры')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издатель')),
                ('platform', models.CharField(max_length=255, verbose_name='Плафторма')),
                ('edition', models.CharField(max_length=100, verbose_name='Тип издания')),
                ('os_req', models.CharField(default='0', max_length=200, verbose_name='Операционная система')),
                ('cpu_req', models.CharField(default='0', max_length=200, verbose_name='Процессор')),
                ('ram_req', models.CharField(default='0', max_length=100, verbose_name='Оперативная память')),
                ('gpu_req', models.CharField(default='0', max_length=200, verbose_name='Видеокарта')),
                ('disk_req', models.CharField(default='0', max_length=50, verbose_name='Место на жестком диске')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-метка')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
