# Generated by Django 5.1.1 on 2024-10-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cpu_req',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='disk_req',
        ),
        migrations.RemoveField(
            model_name='game',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gpu_req',
        ),
        migrations.RemoveField(
            model_name='game',
            name='os_req',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ram_req',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video_url',
        ),
    ]
