# Generated by Django 5.1.1 on 2024-10-31 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_cpu_req_remove_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cpu_req',
            field=models.CharField(default='0', max_length=200, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Краткое описание игры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Разработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='disk_req',
            field=models.CharField(default='0', max_length=50, verbose_name='Место на жестком диске'),
        ),
        migrations.AddField(
            model_name='game',
            name='edition',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Тип издания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gpu_req',
            field=models.CharField(default='0', max_length=200, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='game',
            name='os_req',
            field=models.CharField(default='0', max_length=200, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Плафторма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Издатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ram_req',
            field=models.CharField(default='0', max_length=100, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
    ]
